# Generated by Django 5.0 on 2025-07-23 06:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        ("posts", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AnalyticsInsight",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "insight_type",
                    models.CharField(
                        choices=[
                            ("trend", "Trend Analysis"),
                            ("anomaly", "Anomaly Detection"),
                            ("recommendation", "Recommendation"),
                            ("prediction", "Prediction"),
                            ("comparison", "Comparison"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("platform", models.CharField(blank=True, max_length=20)),
                ("metric_type", models.CharField(blank=True, max_length=20)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("action_items", models.JSONField(default=list)),
                ("is_read", models.BooleanField(default=False)),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("medium", "Medium"), ("high", "High"), ("critical", "Critical")],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="insights", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "analytics_insights",
                "ordering": ["-priority", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PerformanceReport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "report_type",
                    models.CharField(
                        choices=[("weekly", "Weekly"), ("monthly", "Monthly"), ("yearly", "Yearly"), ("custom", "Custom")],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("data", models.JSONField(default=dict)),
                ("pdf_file", models.FileField(blank=True, null=True, upload_to="reports/pdf/")),
                ("csv_file", models.FileField(blank=True, null=True, upload_to="reports/csv/")),
                ("is_generated", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(blank=True, null=True)),
                ("sent_via_email", models.BooleanField(default=False)),
                ("sent_via_slack", models.BooleanField(default=False)),
                ("email_sent_at", models.DateTimeField(blank=True, null=True)),
                ("slack_sent_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reports", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "performance_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalyticsData",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("impressions", "Impressions"),
                            ("reach", "Reach"),
                            ("engagement", "Engagement"),
                            ("likes", "Likes"),
                            ("shares", "Shares"),
                            ("comments", "Comments"),
                            ("saves", "Saves"),
                            ("clicks", "Clicks"),
                            ("followers", "Followers"),
                            ("video_views", "Video Views"),
                            ("profile_views", "Profile Views"),
                        ],
                        max_length=20,
                    ),
                ),
                ("value", models.IntegerField(default=0)),
                ("date", models.DateField()),
                ("platform", models.CharField(max_length=20)),
                ("country", models.CharField(blank=True, max_length=100)),
                ("city", models.CharField(blank=True, max_length=100)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("age_group", models.CharField(blank=True, max_length=20)),
                ("gender", models.CharField(blank=True, max_length=20)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="posts.post",
                    ),
                ),
                (
                    "social_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="authentication.socialmediaaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="analytics", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "analytics_data",
                "indexes": [
                    models.Index(fields=["user", "date"], name="analytics_user_date_idx"),
                    models.Index(fields=["platform", "metric_type"], name="analytics_platform_metric_idx"),
                    models.Index(fields=["post", "metric_type"], name="analytics_post_metric_idx"),
                ],
                "unique_together": {("social_account", "post", "metric_type", "date", "country", "city")},
            },
        ),
        migrations.CreateModel(
            name="BestPerformingPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("platform", models.CharField(max_length=20)),
                (
                    "metric_type",
                    models.CharField(
                        choices=[
                            ("engagement_rate", "Engagement Rate"),
                            ("reach", "Reach"),
                            ("impressions", "Impressions"),
                            ("likes", "Likes"),
                            ("shares", "Shares"),
                            ("comments", "Comments"),
                            ("saves", "Saves"),
                        ],
                        max_length=20,
                    ),
                ),
                ("metric_value", models.FloatField()),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("period_type", models.CharField(max_length=20)),
                ("rank", models.IntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="performance_records", to="posts.post"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="best_posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "best_performing_posts",
                "ordering": ["rank"],
                "unique_together": {("user", "platform", "metric_type", "period_start", "period_end", "rank")},
            },
        ),
        migrations.CreateModel(
            name="CommentAnalytics",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("comment_id", models.CharField(max_length=255)),
                ("comment_text", models.TextField()),
                ("author_username", models.CharField(max_length=255)),
                (
                    "sentiment",
                    models.CharField(
                        choices=[("positive", "Positive"), ("negative", "Negative"), ("neutral", "Neutral")], max_length=20
                    ),
                ),
                ("sentiment_score", models.FloatField(default=0.0)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("likes_count", models.IntegerField(default=0)),
                ("replies_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField()),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="comment_analytics", to="posts.post"
                    ),
                ),
            ],
            options={
                "db_table": "comment_analytics",
                "unique_together": {("post", "comment_id")},
            },
        ),
        migrations.CreateModel(
            name="PlatformAverage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("platform", models.CharField(blank=True, max_length=20)),
                ("avg_impressions", models.FloatField(default=0.0)),
                ("avg_reach", models.FloatField(default=0.0)),
                ("avg_engagement_rate", models.FloatField(default=0.0)),
                ("avg_likes", models.FloatField(default=0.0)),
                ("avg_shares", models.FloatField(default=0.0)),
                ("avg_comments", models.FloatField(default=0.0)),
                ("avg_saves", models.FloatField(default=0.0)),
                ("avg_follower_growth", models.FloatField(default=0.0)),
                ("total_followers", models.IntegerField(default=0)),
                ("period_start", models.DateField()),
                ("period_end", models.DateField()),
                ("period_type", models.CharField(default="monthly", max_length=20)),
                ("calculated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="platform_averages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "platform_averages",
                "unique_together": {("user", "platform", "period_start", "period_end")},
            },
        ),
    ]
