# Generated by Django 5.0 on 2025-08-02 08:25

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="performancereport",
            name="csv_file",
            field=models.FileField(
                blank=True, null=True, storage=apps.core.storage.SupabaseStorage(), upload_to="reports/csv/"
            ),
        ),
        migrations.AlterField(
            model_name="performancereport",
            name="pdf_file",
            field=models.FileField(
                blank=True, null=True, storage=apps.core.storage.SupabaseStorage(), upload_to="reports/pdf/"
            ),
        ),
    ]
