# Generated by Django 5.0.14 on 2026-03-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0002_alter_performancereport_csv_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="analyticsinsight",
            name="data",
            field=models.JSONField(default=dict),
        ),
    ]
