# Generated by Django 5.0 on 2025-07-23 06:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Campaign",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField()),
                ("budget", models.DecimalField(decimal_places=2, max_digits=10)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("active", "Active"),
                            ("paused", "Paused"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("target_niches", models.JSONField(default=list)),
                ("min_followers", models.IntegerField(default=0)),
                ("max_followers", models.IntegerField(blank=True, null=True)),
                ("target_platforms", models.JSONField(default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "creator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_campaigns",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "campaigns",
            },
        ),
        migrations.CreateModel(
            name="Influencer",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("bio", models.TextField(blank=True)),
                (
                    "niche",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("fashion", "Fashion"),
                            ("beauty", "Beauty"),
                            ("fitness", "Fitness"),
                            ("food", "Food"),
                            ("travel", "Travel"),
                            ("tech", "Technology"),
                            ("lifestyle", "Lifestyle"),
                            ("business", "Business"),
                            ("education", "Education"),
                            ("entertainment", "Entertainment"),
                        ],
                        max_length=20,
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("post_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("story_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("reel_rate", models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("is_available", models.BooleanField(default=True)),
                ("total_followers", models.IntegerField(default=0)),
                ("avg_engagement_rate", models.FloatField(default=0.0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="influencer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "influencers",
            },
        ),
        migrations.CreateModel(
            name="CampaignApplication",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("proposed_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("completed", "Completed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("applied_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="influencers.campaign"
                    ),
                ),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="applications", to="influencers.influencer"
                    ),
                ),
            ],
            options={
                "db_table": "campaign_applications",
                "unique_together": {("campaign", "influencer")},
            },
        ),
        migrations.CreateModel(
            name="SocialMediaAccount",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                            ("twitter", "Twitter"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                            ("pinterest", "Pinterest"),
                            ("snapchat", "Snapchat"),
                            ("reddit", "Reddit"),
                        ],
                        max_length=20,
                    ),
                ),
                ("username", models.CharField(max_length=100)),
                ("access_token", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "influencer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_accounts",
                        to="influencers.influencer",
                    ),
                ),
            ],
            options={
                "unique_together": {("influencer", "platform")},
            },
        ),
    ]
