# Generated by Django 5.0 on 2025-07-24 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("influencers", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="SocialMediaAccount",
        ),
    ]
