# Generated by Django 5.0.14 on 2025-08-13 01:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("influencers", "0002_delete_socialmediaaccount"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InfluencerCollaboration",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("agreed_rate", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contract_signed", models.BooleanField(default=False)),
                ("content_submitted", models.BooleanField(default=False)),
                ("content_approved", models.BooleanField(default=False)),
                ("payment_completed", models.BooleanField(default=False)),
                ("deliverables_completed", models.JSONField(blank=True, default=list)),
                ("submission_date", models.DateTimeField(blank=True, null=True)),
                ("approval_date", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("on_hold", "On Hold"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "influencer_collaborations",
            },
        ),
        migrations.CreateModel(
            name="InfluencerPortfolio",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("image", "Image"),
                            ("video", "Video"),
                            ("article", "Article"),
                            ("campaign", "Campaign Results"),
                        ],
                        max_length=20,
                    ),
                ),
                ("media_url", models.URLField(blank=True)),
                ("external_link", models.URLField(blank=True)),
                ("views", models.IntegerField(default=0)),
                ("likes", models.IntegerField(default=0)),
                ("comments", models.IntegerField(default=0)),
                ("shares", models.IntegerField(default=0)),
                ("brand_name", models.CharField(blank=True, max_length=255)),
                ("campaign_type", models.CharField(blank=True, max_length=100)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "influencer_portfolio",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AlterModelOptions(
            name="campaign",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AlterModelOptions(
            name="campaignapplication",
            options={"ordering": ["-applied_at"]},
        ),
        migrations.AddField(
            model_name="campaign",
            name="application_deadline",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="campaign_type",
            field=models.CharField(
                choices=[
                    ("sponsored_post", "Sponsored Post"),
                    ("product_review", "Product Review"),
                    ("brand_partnership", "Brand Partnership"),
                    ("event_promotion", "Event Promotion"),
                    ("giveaway", "Giveaway/Contest"),
                    ("user_generated_content", "UGC Campaign"),
                ],
                default="sponsored_post",
                max_length=30,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="content_guidelines",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="deliverables",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="campaign",
            name="hashtags_required",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="campaign",
            name="is_paid",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="max_participants",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="min_engagement_rate",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="campaign",
            name="products_included",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="campaign",
            name="target_locations",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="campaignapplication",
            name="content_proposal",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="campaignapplication",
            name="feedback",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="campaignapplication",
            name="portfolio_links",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="campaignapplication",
            name="rejection_reason",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="campaignapplication",
            name="timeline_proposal",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="influencer",
            name="collaboration_types",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="influencer",
            name="email_notifications",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="influencer",
            name="is_featured",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="influencer",
            name="languages",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="influencer",
            name="location",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="influencer",
            name="secondary_niches",
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name="influencer",
            name="tier",
            field=models.CharField(
                blank=True,
                choices=[
                    ("nano", "Nano (1K-10K followers)"),
                    ("micro", "Micro (10K-100K followers)"),
                    ("macro", "Macro (100K-1M followers)"),
                    ("mega", "Mega (1M+ followers)"),
                ],
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="influencer",
            name="video_rate",
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name="campaignapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("completed", "Completed"),
                    ("withdrawn", "Withdrawn"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="influencer",
            name="avg_engagement_rate",
            field=models.FloatField(
                default=0.0,
                validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)],
            ),
        ),
        migrations.AlterField(
            model_name="influencer",
            name="bio",
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name="influencer",
            name="niche",
            field=models.CharField(
                blank=True,
                choices=[
                    ("fashion", "Fashion"),
                    ("beauty", "Beauty"),
                    ("fitness", "Fitness"),
                    ("food", "Food"),
                    ("travel", "Travel"),
                    ("tech", "Technology"),
                    ("lifestyle", "Lifestyle"),
                    ("business", "Business"),
                    ("education", "Education"),
                    ("entertainment", "Entertainment"),
                    ("gaming", "Gaming"),
                    ("music", "Music"),
                    ("sports", "Sports"),
                    ("parenting", "Parenting"),
                    ("health", "Health"),
                ],
                max_length=20,
            ),
        ),
        migrations.AddIndex(
            model_name="influencer",
            index=models.Index(fields=["niche", "is_available"], name="influencers_niche_b2f387_idx"),
        ),
        migrations.AddIndex(
            model_name="influencer",
            index=models.Index(fields=["total_followers"], name="influencers_total_f_84c7fd_idx"),
        ),
        migrations.AddIndex(
            model_name="influencer",
            index=models.Index(fields=["tier"], name="influencers_tier_b29b6c_idx"),
        ),
        migrations.AddField(
            model_name="influencercollaboration",
            name="campaign_application",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="collaboration", to="influencers.campaignapplication"
            ),
        ),
        migrations.AddField(
            model_name="influencerportfolio",
            name="influencer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="portfolio", to="influencers.influencer"
            ),
        ),
    ]
