# Generated by Django 5.0 on 2025-08-04 22:57

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="IPBlacklist",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("abuse", "Abuse"),
                            ("spam", "Spam"),
                            ("security", "Security Threat"),
                            ("manual", "Manual Block"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("expires_at", models.DateTimeField(blank=True, help_text="Block expires at this time", null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="IPWhitelist",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ip_address", models.GenericIPAddressField(unique=True)),
                ("description", models.CharField(help_text="Reason for whitelisting", max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("created_by", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["ip_address"],
            },
        ),
        migrations.CreateModel(
            name="RateLimitStats",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("hour", models.IntegerField(help_text="Hour of the day (0-23)")),
                ("total_requests", models.IntegerField(default=0)),
                ("allowed_requests", models.IntegerField(default=0)),
                ("denied_requests", models.IntegerField(default=0)),
                ("burst_protections", models.IntegerField(default=0)),
                ("anonymous_requests", models.IntegerField(default=0)),
                ("authenticated_requests", models.IntegerField(default=0)),
                ("premium_requests", models.IntegerField(default=0)),
                ("admin_requests", models.IntegerField(default=0)),
                ("average_tokens_remaining", models.FloatField(default=0.0)),
                ("average_requests_remaining", models.FloatField(default=0.0)),
                ("peak_requests_per_minute", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-date", "-hour"],
                "unique_together": {("date", "hour")},
            },
        ),
        migrations.CreateModel(
            name="RateLimitLog",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("timestamp", models.DateTimeField(default=django.utils.timezone.now)),
                ("ip_address", models.GenericIPAddressField()),
                ("user_agent", models.TextField(blank=True)),
                ("endpoint", models.CharField(max_length=255)),
                ("method", models.CharField(max_length=10)),
                ("user_type", models.CharField(max_length=20)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("allowed", "Request Allowed"),
                            ("denied", "Request Denied"),
                            ("burst_protection", "Burst Protection Triggered"),
                        ],
                        max_length=20,
                    ),
                ),
                ("algorithm_used", models.CharField(max_length=20)),
                ("tokens_remaining", models.IntegerField(blank=True, null=True)),
                ("requests_remaining", models.IntegerField(blank=True, null=True)),
                ("retry_after", models.IntegerField(blank=True, null=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-timestamp"],
                "indexes": [
                    models.Index(fields=["timestamp", "action"], name="core_rateli_timesta_e4f58f_idx"),
                    models.Index(fields=["user", "timestamp"], name="core_rateli_user_id_b44c8e_idx"),
                    models.Index(fields=["ip_address", "timestamp"], name="core_rateli_ip_addr_33bdf6_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="RateLimitRule",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Rule name for identification", max_length=100)),
                (
                    "user_type",
                    models.CharField(
                        choices=[
                            ("anonymous", "Anonymous"),
                            ("authenticated", "Authenticated"),
                            ("premium", "Premium"),
                            ("admin", "Admin"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "algorithm",
                    models.CharField(
                        choices=[
                            ("token_bucket", "Token Bucket"),
                            ("sliding_window", "Sliding Window"),
                            ("both", "Both Algorithms"),
                        ],
                        default="both",
                        max_length=20,
                    ),
                ),
                ("bucket_capacity", models.IntegerField(default=100, help_text="Maximum tokens in bucket")),
                ("refill_rate", models.FloatField(default=1.0, help_text="Tokens per second refill rate")),
                ("max_requests", models.IntegerField(default=1000, help_text="Maximum requests in window")),
                ("window_size", models.IntegerField(default=3600, help_text="Window size in seconds")),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["user_type", "-created_at"],
                "unique_together": {("user_type", "is_active")},
            },
        ),
    ]
