# Generated by Django 5.0.14 on 2025-08-15 03:41

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SubscriptionTier",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("free", "Free"),
                            ("basic", "Basic"),
                            ("professional", "Professional"),
                            ("enterprise", "Enterprise"),
                        ],
                        max_length=50,
                        unique=True,
                    ),
                ),
                ("display_name", models.CharField(max_length=100)),
                ("description", models.TextField()),
                ("price_monthly", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("price_yearly", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("stripe_price_id_monthly", models.CharField(blank=True, max_length=255)),
                ("stripe_price_id_yearly", models.CharField(blank=True, max_length=255)),
                ("max_social_accounts", models.IntegerField(default=1)),
                ("max_scheduled_posts", models.IntegerField(default=10)),
                ("max_team_members", models.IntegerField(default=1)),
                ("analytics_retention_days", models.IntegerField(default=30)),
                ("api_rate_limit", models.IntegerField(default=1000)),
                ("gohighlevel_integration", models.BooleanField(default=False)),
                ("advanced_analytics", models.BooleanField(default=False)),
                ("priority_support", models.BooleanField(default=False)),
                ("white_label", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "subscription_tiers",
                "ordering": ["price_monthly"],
            },
        ),
        migrations.CreateModel(
            name="GoHighLevelIntegration",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("api_key", models.CharField(blank=True, max_length=255)),
                ("location_id", models.CharField(blank=True, max_length=255)),
                ("sync_contacts", models.BooleanField(default=True)),
                ("sync_opportunities", models.BooleanField(default=True)),
                ("sync_campaigns", models.BooleanField(default=True)),
                ("webhook_url", models.URLField(blank=True)),
                ("webhook_secret", models.CharField(blank=True, max_length=255)),
                ("is_active", models.BooleanField(default=True)),
                ("last_sync_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ghl_integration",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "gohighlevel_integrations",
            },
        ),
        migrations.CreateModel(
            name="UserSubscription",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stripe_customer_id", models.CharField(blank=True, max_length=255)),
                ("stripe_subscription_id", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("past_due", "Past Due"),
                            ("canceled", "Canceled"),
                            ("unpaid", "Unpaid"),
                            ("trialing", "Trialing"),
                        ],
                        default="inactive",
                        max_length=20,
                    ),
                ),
                (
                    "billing_period",
                    models.CharField(choices=[("monthly", "Monthly"), ("yearly", "Yearly")], default="monthly", max_length=10),
                ),
                ("start_date", models.DateTimeField(blank=True, null=True)),
                ("end_date", models.DateTimeField(blank=True, null=True)),
                ("trial_end_date", models.DateTimeField(blank=True, null=True)),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
                ("next_payment_date", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="subscriptions", to="core.subscriptiontier"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="subscription", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "user_subscriptions",
            },
        ),
        migrations.CreateModel(
            name="PaymentHistory",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stripe_payment_intent_id", models.CharField(max_length=255)),
                ("stripe_invoice_id", models.CharField(blank=True, max_length=255)),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        max_length=20,
                    ),
                ),
                ("payment_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payments", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="payments", to="core.usersubscription"
                    ),
                ),
            ],
            options={
                "db_table": "payment_history",
                "ordering": ["-payment_date"],
            },
        ),
        migrations.CreateModel(
            name="CRMContact",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("ghl_contact_id", models.CharField(max_length=255, unique=True)),
                ("first_name", models.CharField(max_length=100)),
                ("last_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=20)),
                ("company", models.CharField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("prospect", "Prospect"),
                            ("customer", "Customer"),
                            ("unsubscribed", "Unsubscribed"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("custom_fields", models.JSONField(blank=True, default=dict)),
                ("social_media_profiles", models.JSONField(blank=True, default=dict)),
                ("last_contacted", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("ghl_created_at", models.DateTimeField(blank=True, null=True)),
                ("ghl_updated_at", models.DateTimeField(blank=True, null=True)),
                ("last_synced_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="crm_contacts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "crm_contacts",
                "indexes": [
                    models.Index(fields=["user", "status"], name="crm_contact_user_id_ca05f3_idx"),
                    models.Index(fields=["email"], name="crm_contact_email_75ee32_idx"),
                    models.Index(fields=["ghl_contact_id"], name="crm_contact_ghl_con_e745fa_idx"),
                ],
                "unique_together": {("user", "ghl_contact_id")},
            },
        ),
    ]
