# Generated by Django 5.0.14 on 2025-08-16 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0003_rate_limit_refactor"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="ipblacklist",
            options={"ordering": ["-created_at"], "verbose_name": "IP Blacklist", "verbose_name_plural": "IP Blacklists"},
        ),
        migrations.AlterModelOptions(
            name="ipwhitelist",
            options={"ordering": ["ip_address"], "verbose_name": "IP Whitelist", "verbose_name_plural": "IP Whitelists"},
        ),
        migrations.AlterModelOptions(
            name="ratelimitlog",
            options={"ordering": ["-blocked_at"], "verbose_name": "Rate Limit Log", "verbose_name_plural": "Rate Limit Logs"},
        ),
        migrations.AlterModelOptions(
            name="ratelimitrule",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Rate Limit Rule",
                "verbose_name_plural": "Rate Limit Rules",
            },
        ),
        migrations.AlterUniqueTogether(
            name="ratelimitrule",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="ipblacklist",
            name="description",
        ),
        migrations.RemoveField(
            model_name="ipblacklist",
            name="expires_at",
        ),
        migrations.AddField(
            model_name="ipblacklist",
            name="blocked_until",
            field=models.DateTimeField(blank=True, help_text="Leave blank for permanent block", null=True),
        ),
        migrations.AlterField(
            model_name="ipblacklist",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="ipblacklist",
            name="reason",
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name="ipwhitelist",
            name="created_by",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="ipwhitelist",
            name="description",
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name="ratelimitlog",
            name="endpoint",
            field=models.CharField(max_length=200),
        ),
        # Remove old retry_after field (integer) and add new one (DateTimeField)
        migrations.RemoveField(
            model_name="ratelimitlog",
            name="retry_after",
        ),
        migrations.AddField(
            model_name="ratelimitlog",
            name="retry_after",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
