# Generated by Django 5.0.14 on 2025-09-01 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_alter_ipblacklist_options_alter_ipwhitelist_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscriptiontier",
            name="approval_workflows",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="best_time_insights",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="bulk_upload_scheduling",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="custom_branding",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="custom_integrations",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="dedicated_account_manager",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="hashtag_suggestions",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="phone_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="sso_support",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="subscriptiontier",
            name="two_factor_auth",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="subscriptiontier",
            name="name",
            field=models.CharField(
                choices=[("free", "Free"), ("professional", "Professional"), ("enterprise", "Enterprise")],
                max_length=50,
                unique=True,
            ),
        ),
    ]
