# Generated by Django 5.0.14 on 2026-03-24 17:36

import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_add_subscription_features"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="ratelimitlog",
            name="core_rateli_ip_addr_e7d153_idx",
        ),
        migrations.RemoveIndex(
            model_name="ratelimitlog",
            name="core_rateli_user_id_95e702_idx",
        ),
        migrations.RemoveIndex(
            model_name="ratelimitlog",
            name="core_rateli_endpoin_32652c_idx",
        ),
        migrations.AddField(
            model_name="ratelimitlog",
            name="action",
            field=models.CharField(default="denied", max_length=20),
        ),
        migrations.AddField(
            model_name="ratelimitlog",
            name="algorithm_used",
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name="ratelimitlog",
            name="metadata",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name="ratelimitlog",
            name="requests_remaining",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="ratelimitlog",
            name="timestamp",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="ratelimitlog",
            name="user_type",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="admin_requests",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="allowed_requests",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="anonymous_requests",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="authenticated_requests",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="average_requests_remaining",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="average_tokens_remaining",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="burst_protections",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="date",
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="denied_requests",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="hour",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="peak_requests_per_minute",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="ratelimitstats",
            name="premium_requests",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="ratelimitlog",
            name="blocked_at",
            field=models.DateTimeField(blank=True, help_text="Specific time of block if applicable", null=True),
        ),
        migrations.AlterModelOptions(
            name="ratelimitlog",
            options={"ordering": ["-timestamp"], "verbose_name": "Rate Limit Log", "verbose_name_plural": "Rate Limit Logs"},
        ),
        migrations.AlterUniqueTogether(
            name="ratelimitstats",
            unique_together=set(),
        ),
        migrations.AlterModelOptions(
            name="ratelimitstats",
            options={
                "ordering": ["-date", "-hour"],
                "verbose_name": "Rate Limit Stats",
                "verbose_name_plural": "Rate Limit Stats",
            },
        ),
        migrations.AlterUniqueTogether(
            name="ratelimitstats",
            unique_together={("date", "hour")},
        ),
        migrations.RemoveField(
            model_name="ratelimitstats",
            name="period_end",
        ),
        migrations.RemoveField(
            model_name="ratelimitstats",
            name="period_start",
        ),
        migrations.AddIndex(
            model_name="ratelimitlog",
            index=models.Index(fields=["ip_address", "-timestamp"], name="core_rateli_ip_addr_2e10ef_idx"),
        ),
        migrations.AddIndex(
            model_name="ratelimitlog",
            index=models.Index(fields=["user", "-timestamp"], name="core_rateli_user_id_fa5d71_idx"),
        ),
        migrations.AddIndex(
            model_name="ratelimitlog",
            index=models.Index(fields=["endpoint", "-timestamp"], name="core_rateli_endpoin_f2b4e8_idx"),
        ),
    ]
