# Generated by Django 5.0 on 2025-07-24 11:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AutomatedMessage",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "trigger_type",
                    models.CharField(
                        choices=[
                            ("new_follower", "New Follower"),
                            ("mention", "Mention"),
                            ("comment", "Comment"),
                            ("dm", "Direct Message"),
                            ("scheduled", "Scheduled"),
                        ],
                        max_length=20,
                    ),
                ),
                ("platform", models.CharField(max_length=50)),
                ("template_content", models.TextField()),
                ("conditions", models.JSONField(default=dict)),
                ("delay_minutes", models.IntegerField(default=0)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="automated_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "automated_messages",
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("platform", models.CharField(max_length=50)),
                ("recipient", models.CharField(max_length=255)),
                ("content", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("failed", "Failed"),
                            ("delivered", "Delivered"),
                            ("read", "Read"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[("low", "Low"), ("normal", "Normal"), ("high", "High"), ("urgent", "Urgent")],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("scheduled_time", models.DateTimeField(blank=True, null=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("response_received", models.BooleanField(default=False)),
                ("response_content", models.TextField(blank=True)),
                ("response_time", models.DateTimeField(blank=True, null=True)),
                ("message_type", models.CharField(default="direct", max_length=50)),
                ("campaign_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="messages", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "messages",
                "ordering": ["-created_at"],
            },
        ),
    ]
