# Generated by Django 5.0 on 2025-08-08 05:56

import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("messaging", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="automatedmessage",
            old_name="is_active",
            new_name="active",
        ),
        migrations.RemoveField(
            model_name="message",
            name="campaign_id",
        ),
        migrations.RemoveField(
            model_name="message",
            name="response_content",
        ),
        migrations.RemoveField(
            model_name="message",
            name="response_received",
        ),
        migrations.RemoveField(
            model_name="message",
            name="response_time",
        ),
        migrations.RemoveField(
            model_name="message",
            name="scheduled_time",
        ),
        migrations.RemoveField(
            model_name="message",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="automatedmessage",
            name="content_template",
            field=models.TextField(
                default="Hello {username}! Thank you for your interaction.",
                help_text="Use placeholders like {username}, {follower_count}, etc.",
            ),
        ),
        migrations.AddField(
            model_name="automatedmessage",
            name="trigger",
            field=models.CharField(
                choices=[
                    ("new_follower", "New Follower"),
                    ("mention", "Mention"),
                    ("comment", "Comment"),
                    ("direct_message", "Direct Message"),
                ],
                default="direct_message",
                max_length=50,
            ),
        ),
        # Ensure id stays UUID for AutomatedMessage
        migrations.AlterField(
            model_name="automatedmessage",
            name="id",
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        # Ensure id stays UUID for Message
        migrations.AlterField(
            model_name="message",
            name="id",
            field=models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="automatedmessage",
            name="delay_minutes",
            field=models.PositiveIntegerField(default=0, help_text="Delay in minutes before sending"),
        ),
        migrations.AlterField(
            model_name="automatedmessage",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram", "Instagram"),
                    ("twitter", "Twitter"),
                    ("facebook", "Facebook"),
                    ("linkedin", "LinkedIn"),
                    ("email", "Email"),
                    ("sms", "SMS"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="message_type",
            field=models.CharField(
                choices=[("direct", "Direct"), ("automated", "Automated"), ("broadcast", "Broadcast")],
                default="direct",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="platform",
            field=models.CharField(
                choices=[
                    ("instagram", "Instagram"),
                    ("twitter", "Twitter"),
                    ("facebook", "Facebook"),
                    ("linkedin", "LinkedIn"),
                    ("email", "Email"),
                    ("sms", "SMS"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="priority",
            field=models.CharField(
                choices=[("high", "High"), ("normal", "Normal"), ("low", "Low")], default="normal", max_length=10
            ),
        ),
        migrations.AlterField(
            model_name="message",
            name="status",
            field=models.CharField(
                choices=[("pending", "Pending"), ("sent", "Sent"), ("failed", "Failed"), ("delivered", "Delivered")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.RemoveField(
            model_name="automatedmessage",
            name="conditions",
        ),
        migrations.RemoveField(
            model_name="automatedmessage",
            name="name",
        ),
        migrations.RemoveField(
            model_name="automatedmessage",
            name="template_content",
        ),
        migrations.RemoveField(
            model_name="automatedmessage",
            name="trigger_type",
        ),
        migrations.AlterUniqueTogether(
            name="automatedmessage",
            unique_together={("user", "platform", "trigger")},
        ),
    ]
