# Generated by Django 5.0.14 on 2025-08-18 09:51

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("core", "0004_alter_ipblacklist_options_alter_ipwhitelist_options_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Invoice",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stripe_invoice_id", models.CharField(max_length=255, unique=True)),
                ("invoice_number", models.CharField(max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("open", "Open"),
                            ("paid", "Paid"),
                            ("uncollectible", "Uncollectible"),
                            ("void", "Void"),
                        ],
                        max_length=20,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
                ("tax", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("total", models.DecimalField(decimal_places=2, max_digits=10)),
                ("amount_paid", models.DecimalField(decimal_places=2, default=Decimal("0.00"), max_digits=10)),
                ("amount_due", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                ("invoice_date", models.DateTimeField()),
                ("due_date", models.DateTimeField()),
                ("paid_at", models.DateTimeField(blank=True, null=True)),
                ("hosted_invoice_url", models.URLField(blank=True)),
                ("invoice_pdf_url", models.URLField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to="core.usersubscription"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="invoices", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "invoices",
                "ordering": ["-invoice_date"],
            },
        ),
        migrations.CreateModel(
            name="PaymentMethod",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("stripe_payment_method_id", models.CharField(max_length=255)),
                (
                    "type",
                    models.CharField(
                        choices=[("card", "Credit/Debit Card"), ("bank_account", "Bank Account"), ("paypal", "PayPal")],
                        max_length=20,
                    ),
                ),
                ("is_default", models.BooleanField(default=False)),
                ("last_four", models.CharField(blank=True, max_length=4)),
                ("brand", models.CharField(blank=True, max_length=20)),
                ("exp_month", models.IntegerField(blank=True, null=True)),
                ("exp_year", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment_methods",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "payment_methods",
                "ordering": ["-is_default", "-created_at"],
            },
        ),
    ]
