# Generated by Django 5.0 on 2025-07-24 11:01

from django.db import migrations, models


def migrate_time_format_data(apps, schema_editor):
    """Convert existing time format data to new format"""
    UserProfile = apps.get_model('authentication', 'UserProfile')
    
    # Mapping from old format to new format
    format_mapping = {
        'standard': '12h',
        '12h': '12h',
        '24h': '24h',
        'twelve': '12h',
        'twentyfour': '24h',
        'ampm': '12h',
        'military': '24h',
    }
    
    for profile in UserProfile.objects.all():
        old_format = profile.time_format.lower() if profile.time_format else 'standard'
        new_format = format_mapping.get(old_format, '12h')  # Default to 12h
        profile.time_format = new_format
        profile.save()


def reverse_migrate_time_format_data(apps, schema_editor):
    """Reverse the time format migration"""
    UserProfile = apps.get_model('authentication', 'UserProfile')
    
    # Reverse mapping
    reverse_mapping = {
        '12h': 'standard',
        '24h': '24h',
    }
    
    for profile in UserProfile.objects.all():
        old_format = profile.time_format
        new_format = reverse_mapping.get(old_format, 'standard')
        profile.time_format = new_format
        profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0001_initial"),
    ]

    operations = [
        # First, add timezone field
        migrations.AddField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
        
        # Then migrate the data
        migrations.RunPython(
            migrate_time_format_data,
            reverse_migrate_time_format_data,
        ),
        
        # Finally, alter the field constraints
        migrations.AlterField(
            model_name="userprofile",
            name="time_format",
            field=models.CharField(choices=[("12h", "12 Hour"), ("24h", "24 Hour")], default="12h", max_length=3),
        ),
    ]
