# Generated by Django 5.0 on 2025-08-02 08:25

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0002_fix_time_format_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(blank=True, null=True, storage=apps.core.storage.SupabaseStorage(), upload_to="avatars/"),
        ),
    ]
