# Generated by Django 5.0 on 2025-08-08 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0005_remove_userprofile_time_format_alter_teammember_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="time_format",
            field=models.CharField(choices=[("12h", "12 Hour"), ("24h", "24 Hour")], default="12h", max_length=3),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="subscription_type",
            field=models.CharField(default="free", max_length=20),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="timezone",
            field=models.CharField(default="UTC", max_length=50),
        ),
    ]
