# Generated by Django 5.0.14 on 2025-09-01 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0007_scheduledpost"),
        ("core", "0005_add_subscription_features"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="userprofile",
            name="subscription_type",
        ),
        migrations.AddField(
            model_name="userprofile",
            name="subscription_tier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="user_profiles",
                to="core.subscriptiontier",
            ),
        ),
    ]
