# Generated by Django 5.0.14 on 2025-09-01 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0008_change_subscription_type_to_tier"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="is_trial_active",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trial_end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trial_expired_notified",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="trial_start_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
