# Generated by Django 5.0.14 on 2025-09-07 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0009_add_trial_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediaaccount",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
