# Generated by Django 5.0.14 on 2025-09-18 11:53

import apps.core.storage
import apps.core.upload_paths
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authentication", "0011_passwordresettoken"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.core.storage.SupabaseStorage(),
                upload_to=apps.core.upload_paths.user_avatar_upload_path,
            ),
        ),
    ]
