# Generated by Django 5.0.14 on 2025-08-12 08:07

import apps.core.storage
import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("original_name", models.CharField(max_length=255)),
                (
                    "file",
                    models.FileField(
                        storage=apps.core.storage.SupabaseStorage(),
                        upload_to="media/user_uploads/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "gif",
                                    "webp",
                                    "svg",
                                    "mp4",
                                    "mov",
                                    "avi",
                                    "wmv",
                                    "flv",
                                    "webm",
                                    "mp3",
                                    "wav",
                                    "ogg",
                                    "aac",
                                ]
                            )
                        ],
                    ),
                ),
                ("size", models.BigIntegerField()),
                (
                    "media_type",
                    models.CharField(choices=[("image", "Image"), ("video", "Video"), ("audio", "Audio")], max_length=10),
                ),
                ("mime_type", models.CharField(max_length=100)),
                ("width", models.PositiveIntegerField(blank=True, null=True)),
                ("height", models.PositiveIntegerField(blank=True, null=True)),
                ("duration", models.FloatField(blank=True, null=True)),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True, null=True, storage=apps.core.storage.SupabaseStorage(), upload_to="media/thumbnails/"
                    ),
                ),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="media_files", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="MediaFolder",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="media.mediafolder"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="media_folders", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="MediaFileFolder",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("media_file", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="media.mediafile")),
                ("folder", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="media.mediafolder")),
            ],
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(fields=["user", "media_type"], name="media_media_user_id_f98667_idx"),
        ),
        migrations.AddIndex(
            model_name="mediafile",
            index=models.Index(fields=["user", "created_at"], name="media_media_user_id_998755_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="mediafolder",
            unique_together={("user", "name", "parent")},
        ),
        migrations.AlterUniqueTogether(
            name="mediafilefolder",
            unique_together={("media_file", "folder")},
        ),
    ]
