# Generated by Django 5.0.14 on 2025-09-18 11:53

import apps.core.storage
import apps.core.upload_paths
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("media", "0002_enhanced_media_features"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="mediafile",
            name="media_files_user_folder_idx",
        ),
        migrations.RenameIndex(
            model_name="mediafolder",
            new_name="media_media_user_id_f41f4a_idx",
            old_name="media_folders_user_parent_idx",
        ),
        migrations.RenameIndex(
            model_name="mediafolder",
            new_name="media_media_user_id_028dac_idx",
            old_name="media_folders_user_name_idx",
        ),
        migrations.RenameIndex(
            model_name="mediauploadbatch",
            new_name="media_media_user_id_f3c6ed_idx",
            old_name="media_batches_user_status_idx",
        ),
        migrations.RenameIndex(
            model_name="mediauploadbatch",
            new_name="media_media_user_id_501d9d_idx",
            old_name="media_batches_user_created_idx",
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="file",
            field=models.FileField(
                storage=apps.core.storage.SupabaseStorage(),
                upload_to=apps.core.upload_paths.user_media_upload_path,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "jpg",
                            "jpeg",
                            "png",
                            "gif",
                            "webp",
                            "svg",
                            "mp4",
                            "mov",
                            "avi",
                            "wmv",
                            "flv",
                            "webm",
                            "mp3",
                            "wav",
                            "ogg",
                            "aac",
                        ]
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="mediafile",
            name="thumbnail",
            field=models.ImageField(
                blank=True,
                null=True,
                storage=apps.core.storage.SupabaseStorage(),
                upload_to=apps.core.upload_paths.user_thumbnail_upload_path,
            ),
        ),
    ]
