# Generated by Django 5.0 on 2025-08-08 04:44

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaAccount",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter/X"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                    ),
                ),
                ("platform_user_id", models.CharField(max_length=100)),
                ("username", models.CharField(max_length=100)),
                ("display_name", models.CharField(blank=True, max_length=200)),
                ("profile_image_url", models.URLField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("followers_count", models.IntegerField(default=0)),
                ("following_count", models.IntegerField(default=0)),
                ("posts_count", models.IntegerField(default=0)),
                ("access_token", models.TextField(blank=True)),
                ("refresh_token", models.TextField(blank=True)),
                ("token_expires_at", models.DateTimeField(blank=True, null=True)),
                ("connected_at", models.DateTimeField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("last_sync", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="connected_social_accounts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-connected_at"],
                "unique_together": {("user", "platform", "platform_user_id")},
            },
        ),
        migrations.CreateModel(
            name="SocialMediaPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("media_urls", models.JSONField(blank=True, default=list)),
                ("hashtags", models.JSONField(blank=True, default=list)),
                ("mentions", models.JSONField(blank=True, default=list)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("platforms", models.JSONField(default=list)),
                ("platform_posts", models.JSONField(blank=True, default=dict)),
                ("total_likes", models.IntegerField(default=0)),
                ("total_shares", models.IntegerField(default=0)),
                ("total_comments", models.IntegerField(default=0)),
                ("total_views", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="social_posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TwitterPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tweet_text", models.TextField(max_length=280)),
                ("media_paths", models.JSONField(blank=True, default=list)),
                ("tweet_id", models.CharField(blank=True, max_length=100)),
                ("in_reply_to_tweet_id", models.CharField(blank=True, max_length=100)),
                ("is_retweet", models.BooleanField(default=False)),
                ("is_quote_tweet", models.BooleanField(default=False)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("retweet_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("reply_count", models.IntegerField(default=0)),
                ("quote_count", models.IntegerField(default=0)),
                ("impression_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("last_analytics_update", models.DateTimeField(blank=True, null=True)),
                (
                    "social_media_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="twitter_posts",
                        to="integrations.socialmediaaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="twitter_posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ScheduledPostQueue",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content_type", models.CharField(max_length=50)),
                ("object_id", models.UUIDField()),
                ("scheduled_at", models.DateTimeField()),
                (
                    "platform",
                    models.CharField(
                        choices=[
                            ("twitter", "Twitter/X"),
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("tiktok", "TikTok"),
                            ("youtube", "YouTube"),
                        ],
                        max_length=20,
                    ),
                ),
                ("is_processed", models.BooleanField(default=False)),
                ("processed_at", models.DateTimeField(blank=True, null=True)),
                ("attempts", models.IntegerField(default=0)),
                ("max_attempts", models.IntegerField(default=3)),
                ("error_message", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                "ordering": ["scheduled_at"],
                "indexes": [
                    models.Index(fields=["scheduled_at", "is_processed"], name="integration_schedul_f3b047_idx"),
                    models.Index(fields=["platform", "is_processed"], name="integration_platfor_cb9af0_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaAnalytics",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("date", models.DateField()),
                ("followers_gained", models.IntegerField(default=0)),
                ("followers_lost", models.IntegerField(default=0)),
                ("posts_created", models.IntegerField(default=0)),
                ("total_likes", models.IntegerField(default=0)),
                ("total_shares", models.IntegerField(default=0)),
                ("total_comments", models.IntegerField(default=0)),
                ("total_views", models.IntegerField(default=0)),
                ("total_impressions", models.IntegerField(default=0)),
                ("engagement_rate", models.FloatField(default=0.0)),
                ("reach", models.IntegerField(default=0)),
                ("platform_specific_metrics", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "social_media_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analytics",
                        to="integrations.socialmediaaccount",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "unique_together": {("social_media_account", "date")},
            },
        ),
    ]
