# Generated by Django 5.0.14 on 2025-08-11 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="socialmediaaccount",
            name="refresh_token",
            field=models.TextField(blank=True, null=True),
        ),
    ]
