# Generated by Django 5.0.14 on 2025-08-16 04:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0003_socialmediaaccount_signature_integrationconnection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="TikTokPost",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("title", models.CharField(blank=True, max_length=150)),
                ("description", models.TextField(blank=True, max_length=2200)),
                ("video_path", models.CharField(max_length=500)),
                ("tiktok_video_id", models.CharField(blank=True, max_length=100)),
                ("upload_id", models.CharField(blank=True, max_length=100)),
                ("publish_id", models.CharField(blank=True, max_length=100)),
                ("duration_ms", models.IntegerField(blank=True, null=True)),
                ("video_width", models.IntegerField(blank=True, null=True)),
                ("video_height", models.IntegerField(blank=True, null=True)),
                ("file_size_bytes", models.BigIntegerField(blank=True, null=True)),
                (
                    "privacy_level",
                    models.CharField(
                        choices=[
                            ("PUBLIC_TO_EVERYONE", "Public to Everyone"),
                            ("MUTUAL_FOLLOW_FRIEND", "Friends"),
                            ("SELF_ONLY", "Private"),
                        ],
                        default="PUBLIC_TO_EVERYONE",
                        max_length=30,
                    ),
                ),
                ("disable_duet", models.BooleanField(default=False)),
                ("disable_comment", models.BooleanField(default=False)),
                ("disable_stitch", models.BooleanField(default=False)),
                ("brand_content_toggle", models.BooleanField(default=False)),
                ("brand_organic_toggle", models.BooleanField(default=False)),
                ("video_cover_timestamp_ms", models.IntegerField(default=1000)),
                ("hashtags", models.JSONField(blank=True, default=list)),
                ("mentions", models.JSONField(blank=True, default=list)),
                ("scheduled_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("publishing", "Publishing"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("deleted", "Deleted"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("view_count", models.IntegerField(default=0)),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("share_count", models.IntegerField(default=0)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("max_retries", models.IntegerField(default=3)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "social_media_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tiktok_posts",
                        to="integrations.socialmediaaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tiktok_posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
