# Generated by Django 5.0.14 on 2025-09-18 11:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("integrations", "0004_tiktokpost"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaSet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(help_text="Name for this social media set", max_length=100)),
                ("description", models.TextField(blank=True, help_text="Optional description for this set")),
                ("color", models.CharField(default="#3B82F6", help_text="Hex color code for UI representation", max_length=7)),
                ("icon", models.CharField(default="users", help_text="Icon name for UI representation", max_length=50)),
                (
                    "is_global",
                    models.BooleanField(default=False, help_text="Global set for all new accounts (only one per user)"),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_default_for_posting",
                    models.BooleanField(default=False, help_text="Use this set as default when posting to multiple platforms"),
                ),
                (
                    "auto_assign_new_accounts",
                    models.BooleanField(default=False, help_text="Automatically assign new social accounts to this set"),
                ),
                (
                    "auto_assign_platforms",
                    models.JSONField(
                        blank=True, default=list, help_text="List of platforms to auto-assign (empty means all platforms)"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_sets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["is_global", "-is_default_for_posting", "name"],
            },
        ),
        migrations.CreateModel(
            name="SocialMediaSetMembership",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "is_primary_set",
                    models.BooleanField(default=False, help_text="Whether this is the primary set for this account"),
                ),
                (
                    "custom_name",
                    models.CharField(blank=True, help_text="Custom name for this account within this set", max_length=100),
                ),
                (
                    "posting_enabled",
                    models.BooleanField(default=True, help_text="Whether posting is enabled for this account in this set"),
                ),
                (
                    "post_order",
                    models.PositiveIntegerField(default=0, help_text="Order for posting when posting to multiple accounts"),
                ),
                (
                    "added_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who added this account to the set",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "social_account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="set_memberships",
                        to="integrations.socialmediaaccount",
                    ),
                ),
                (
                    "social_set",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="memberships",
                        to="integrations.socialmediaset",
                    ),
                ),
            ],
            options={
                "ordering": ["post_order", "added_at"],
            },
        ),
        migrations.AddField(
            model_name="socialmediaaccount",
            name="social_sets",
            field=models.ManyToManyField(
                blank=True,
                help_text="Social media sets this account belongs to",
                related_name="social_accounts",
                through="integrations.SocialMediaSetMembership",
                to="integrations.socialmediaset",
            ),
        ),
        migrations.AddIndex(
            model_name="socialmediaset",
            index=models.Index(fields=["user", "is_global"], name="integration_user_id_17fc57_idx"),
        ),
        migrations.AddIndex(
            model_name="socialmediaset",
            index=models.Index(fields=["user", "is_active"], name="integration_user_id_0e7e7e_idx"),
        ),
        migrations.AddIndex(
            model_name="socialmediaset",
            index=models.Index(fields=["user", "is_default_for_posting"], name="integration_user_id_ccfbd3_idx"),
        ),
        migrations.AddConstraint(
            model_name="socialmediaset",
            constraint=models.UniqueConstraint(fields=("user", "name"), name="unique_set_name_per_user"),
        ),
        migrations.AddIndex(
            model_name="socialmediasetmembership",
            index=models.Index(fields=["social_set", "posting_enabled"], name="integration_social__4c83b4_idx"),
        ),
        migrations.AddIndex(
            model_name="socialmediasetmembership",
            index=models.Index(fields=["social_account", "is_primary_set"], name="integration_social__709622_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="socialmediasetmembership",
            unique_together={("social_set", "social_account")},
        ),
    ]
