# Generated by Django 5.0.14 on 2026-06-15 02:14

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0005_add_social_media_sets'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIAgent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('persona', models.TextField(help_text='System instructions or persona prompt for the agent')),
                ('platform', models.CharField(default='all', help_text='Default platform for this agent (e.g., twitter, linkedin, instagram, tiktok, all)', max_length=20)),
                ('tone', models.CharField(default='professional', help_text="Agent's writing tone/style (e.g., professional, humorous, educational, persuasive, witty)", max_length=50)),
                ('temperature', models.FloatField(default=0.7, help_text='Creativity temperature (0.0 to 1.0)')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_agents', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_agents',
                'ordering': ['-created_at'],
            },
        ),
    ]
