# Generated by Django 5.0.14 on 2026-06-26 12:23

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integrations', '0006_aiagent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsageLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('feature', models.CharField(db_index=True, max_length=50)),
                ('platform', models.CharField(blank=True, max_length=20)),
                ('model_used', models.CharField(default='gemini-2.5-flash', max_length=50)),
                ('api_calls_made', models.IntegerField(default=1)),
                ('method', models.CharField(max_length=30)),
                ('latency_ms', models.IntegerField()),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True)),
                ('input_tokens', models.IntegerField(blank=True, null=True)),
                ('output_tokens', models.IntegerField(blank=True, null=True)),
                ('feedback_action', models.CharField(blank=True, max_length=20)),
                ('feedback_metadata', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('agent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='integrations.aiagent')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_usage_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'created_at'], name='ai_usage_lo_user_id_3f9263_idx'), models.Index(fields=['feature', 'created_at'], name='ai_usage_lo_feature_ccd6e0_idx')],
            },
        ),
    ]
