# Generated by Django 5.0 on 2025-07-23 06:11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("authentication", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Holiday",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("date", models.DateField()),
                ("country", models.CharField(default="US", max_length=100)),
                ("category", models.CharField(blank=True, max_length=100)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "db_table": "holidays",
                "unique_together": {("name", "date", "country")},
            },
        ),
        migrations.CreateModel(
            name="PostSuggestion",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "suggestion_type",
                    models.CharField(
                        choices=[
                            ("content", "Content Suggestion"),
                            ("hashtag", "Hashtag Suggestion"),
                            ("timing", "Timing Suggestion"),
                        ],
                        max_length=20,
                    ),
                ),
                ("platform", models.CharField(max_length=20)),
                ("content", models.TextField()),
                ("confidence_score", models.FloatField(default=0.0)),
                ("is_used", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_suggestions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "post_suggestions",
                "ordering": ["-confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PostTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("caption", models.TextField(blank=True)),
                ("hashtags", models.TextField(blank=True)),
                (
                    "post_type",
                    models.CharField(
                        choices=[("post", "Post"), ("story", "Story"), ("reel", "Reel"), ("video", "Video")],
                        default="post",
                        max_length=20,
                    ),
                ),
                ("platforms", models.JSONField(default=list, help_text="List of platforms this template is for")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="post_templates", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "post_templates",
            },
        ),
        migrations.CreateModel(
            name="SocialSet",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("accounts", models.ManyToManyField(related_name="social_sets", to="authentication.socialmediaaccount")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="social_sets", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
            options={
                "db_table": "social_sets",
            },
        ),
        migrations.CreateModel(
            name="Post",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("content", models.TextField()),
                ("caption", models.TextField(blank=True)),
                ("hashtags", models.TextField(blank=True, help_text="Comma-separated hashtags")),
                ("image", models.ImageField(blank=True, null=True, upload_to="posts/images/")),
                ("video", models.FileField(blank=True, null=True, upload_to="posts/videos/")),
                ("media_url", models.URLField(blank=True, help_text="External media URL")),
                ("scheduled_time", models.DateTimeField()),
                ("timezone", models.CharField(default="UTC", max_length=50)),
                (
                    "post_type",
                    models.CharField(
                        choices=[("post", "Post"), ("story", "Story"), ("reel", "Reel"), ("video", "Video")],
                        default="post",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("scheduled", "Scheduled"),
                            ("published", "Published"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("platform", models.CharField(max_length=20)),
                ("location", models.CharField(blank=True, max_length=255)),
                ("latitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("longitude", models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ("tagged_users", models.TextField(blank=True, help_text="Comma-separated usernames")),
                ("is_locked", models.BooleanField(default=False, help_text="Prevent editing when locked")),
                ("is_template", models.BooleanField(default=False, help_text="Save as reusable template")),
                ("external_post_id", models.CharField(blank=True, help_text="Platform-specific post ID", max_length=255)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("retry_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "social_account",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="authentication.socialmediaaccount",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="posts", to=settings.AUTH_USER_MODEL
                    ),
                ),
                (
                    "social_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="posts",
                        to="posts.socialset",
                    ),
                ),
            ],
            options={
                "db_table": "posts",
                "ordering": ["-scheduled_time"],
            },
        ),
    ]
