# Generated by Django 5.0 on 2025-08-02 08:25

import apps.core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("posts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="image",
            field=models.ImageField(
                blank=True, null=True, storage=apps.core.storage.SupabaseStorage(), upload_to="posts/images/"
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="video",
            field=models.FileField(
                blank=True, null=True, storage=apps.core.storage.SupabaseStorage(), upload_to="posts/videos/"
            ),
        ),
    ]
