# Generated by Django 5.0.14 on 2026-09-18 19:19

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_approval_feedback_post_approval_reviewer_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='is_evergreen',
            field=models.BooleanField(default=False, help_text='Automatically re-queue post after successful publication'),
        ),
        migrations.AddField(
            model_name='post',
            name='last_recycled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='max_recycle_count',
            field=models.IntegerField(blank=True, help_text='Maximum recycles allowed (null for unlimited)', null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='original_post',
            field=models.ForeignKey(blank=True, help_text='Original post this instance was recycled from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recycled_instances', to='posts.post'),
        ),
        migrations.AddField(
            model_name='post',
            name='recycle_count',
            field=models.IntegerField(default=0, help_text='Number of times this post has been recycled'),
        ),
        migrations.AddField(
            model_name='post',
            name='recycle_interval_days',
            field=models.IntegerField(blank=True, default=30, help_text='Days to wait before recycling this post', null=True),
        ),
        migrations.CreateModel(
            name='PostingScheduleSlot',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(blank=True, help_text='Specific platform or blank for all platforms', max_length=50)),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')])),
                ('time', models.TimeField(help_text='Time of day for this slot (e.g. 10:00:00)')),
                ('timezone', models.CharField(default='UTC', max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posting_schedule_slots', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'posting_schedule_slots',
                'ordering': ['day_of_week', 'time'],
                'unique_together': {('user', 'platform', 'day_of_week', 'time')},
            },
        ),
    ]
